### PR TITLE
Tom branch

### PR DESCRIPTION
**Pull request by ttlaz123**
added some new features to the tsv file, which i guess isn't a tsv file anymore

### CODE REVIEW

**Comment by loafyyy** [comment]
L o l  hi Tom

**Comment by robinz62** [comment]
lol i regret writing this in python looking at python code makes my head hurt

also rip busy right now 
image

**Comment by loafyyy** [comment]
:shipit:

**Comment by ttlaz123** [comment]
> L o l  hi Tom

how do i respond

**Comment by robinz62** [comment]
Closing this PR as the project has been heavily refactored to increase mental health. Based on the diff, the only features present in this PR but not in the master branch seem to be some existing analyses performed with restricted time range. This seems minor and shouldn't be time-consuming to the new code.

**Pull request closed without merging**
